version: '3'
services:
  app:
    build: .
    environment:
      RAILS_ENV: 'development'
      DB_USERNAME: 'postgres'
      DB_HOST: db
      REDIS_HOST: redis
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    links:
      - db
      - redis
  db:
    image: postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
  redis:
    image: redis
    
